---
- name: Gather facts
  hosts: all
  gather_facts: yes

- hosts: blag
  roles: 
    - common
    - xorg-virtualbox
    - i3gui

- hosts: dingbat
  roles:
    - common
    - xorg-intel
    - applications
    - gnome

- hosts: wombat
  roles:
    - common
    - xorg-intel
    - applications
    - gnome
