---
- name: Install gui applications
  pacman:
    name:
      - libreoffice-fresh
      - libreoffice-extension-texmaths
      - libreoffice-extension-writer2latex
      - hunspell
      - hunspell-en_AU
      - hyphen
      - hyphen-en
      - jre8-openjdk
      - jdk-openjdk
      - firefox
      - chromium
      - gedit
      - gedit-plugins
      - keepassxc
      - syncthing
      - mpd
      - ncmpc
      - libmpdclient
      - libmpd
      - gvfs
      - dfc         # nicer df
      - ncdu        # ncurses disk usage
      - hexyl       # hex editor
      - python-pip
      - bluez-utils

- name: Copy mpd configuration
  copy:
    src: mpd.conf
    dest: /home/michael/.config/mpd/
    owner: michael

- name: Enable bluetooth
  lineinfile:
    dest: /etc/bluetooth/main.conf
    regexp: '#*AutoEnable*=*false'
    line: 'AutoEnable=true'
    backrefs: yes

- name: Start bluetooth service
  service:
    name: bluetooth
    enabled: yes
    state: started
