---
- name: Install dev applications
  aur:
    skip_installed: true
    name:
      - visual-studio-code-bin
      - pycharm-professional
      - webstorm-jre
      - gitkraken
  become: yes
  become_user: aur_builder
