---
- name: Install xorg / fonts
  pacman: 
    name: 
      - xorg-server
      - xorg-xinit 
      - xorg-xsetroot # For setting the default cursor
      - xorg-xprop # For querying info about open windows
      - xorg-xev # For printing x server events
      - xorg-xfontsel # For visually selecting font strings
      - xorg-xrandr
      - xorg-xbacklight      
      - tlp
      - tlp-rdw
      - htop
      - powertop
      - noto-fonts        # install a bunch of fonts
      - noto-fonts-extra 
      - ttf-anonymous-pro 
      - ttf-bitstream-vera 
      - ttf-caladea 
      - ttf-carlito 
      - ttf-cormorant 
      - ttf-croscore 
      - ttf-dejavu 
      - ttf-droid 
      - ttf-fantasque-sans-mono 
      - ttf-fira-code 
      - ttf-fira-mono 
      - ttf-fira-sans 
      - ttf-font-awesome 
      - ttf-freefont 
      - ttf-gentium 
      - ttf-hack 
      - ttf-ibm-plex 
      - ttf-inconsolata 
      - ttf-ionicons 
      - ttf-liberation 
      - ttf-linux-libertine 
      - ttf-opensans 
      - ttf-roboto 
      - ttf-ubuntu-font-family
      - alsa-utils

- name: Install additional fonts
  aur:
    skip_installed: true
    name:
      - ttf-ms-fonts
      - ttf-iosevka-term
      - ttf-symbola
      - ttf-emojione-color
      - ttf-oswald
      - ttf-cheapskate 
      - siji-git
      - termsyn-font
      - ttf-material-icons
      - nerd-fonts-complete
  become: yes
  become_user: aur_builder

- name: Enable powersaving utility
  systemd:
    name: tlp.service	
    enabled: yes
    state: started

- name: Enalble sleep
  systemd:
    name: tlp-sleep.service
    enabled: yes
    state: started

- name: Enable ssd trim
  systemd:
    name: fstrim.timer
    enabled: yes
    state: started

- name: Disalbe rf-kill, managed by tlp
  systemd:
     name: systemd-rfkill.service     
     masked: yes
     state: stopped

- name: Disable rf-kill socket
  systemd:
    name:  systemd-rfkill.socket
    masked: yes
    state: stopped

- name: Install gui applications
  pacman:
    name: 
      - libreoffice-fresh 
      - libreoffice-extension-texmaths 
      - libreoffice-extension-writer2latex 
      - hunspell 
      - hunspell-en_AU 
      - hyphen 
      - hyphen-en 
      - jre8-openjdk 
      - jdk-openjdk
      - firefox 
      - chromium
      - gedit
      - gedit-plugins
      - keepassxc
      - syncthing
      - mpd
      - ncmpc
      - libmpdclient
      - libmpd
      - thunar
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - gvfs
      - xfce4-panel
      - tumbler
      - dfc         # nicer df
      - ncdu        # ncurses disk usage
      - hexyl       # hex editor
      - python-pip

- name: Install I3 window manager details
  pacman: 
    name:
      - i3
      - rxvt-unicode
      - dmenu
      - compton
      - feh
      - rofi
      - playerctl 
      - neofetch

- name: Install powerline
  pip:
    name: powerline-shell

- name: Copy mpd configuration
  copy:
    src: mpd.conf
    dest: /home/michael/.config/mpd/
    owner: michael

- name: Copy xinit utilities
  copy:
    src: .xinitrc
    dest: /home/michael/.xinitrc
    owner: michael

- name: Create default bash profile
  copy:
    src: .bash_profile
    dest: /home/michael/.bash_profile
    owner: michael

- name: Create an .Xresources
  copy: 
    src: .Xresources
    dest: /home/michael/.Xresources
    owner: michael

- name: Copy compton conf
  copy:
    src: compton.conf
    dest: /home/michael/.config/compton/
    owner: michael

- name: copy i3 configuration
  copy: 
    src: i3/config
    dest: /home/michael/.config/i3
    owner: michael

- name: Copy polybar configuration
  copy:
    src: polybar/
    dest: /home/michael/.config/polybar/
    owner: michael
    mode: preserve

- name: Copy powerline shell config
  copy:
    src: powerline-shell/config.json
    dest: /home/michael/.config/powerline-shell/
    owner: michael

- name: Install i3 apps/rxvt extensions
  aur:
    skip_installed: true
    name: 
      - urxvt-fullscreen
      - urxvt-resize-font-git  
      - urxvt-vtwheel
      - polybar
      - networkmanager-dmenu-git
  become: yes
  become_user: aur_builder


- name: Install dev applications
  aur:
    skip_installed: true
    name:
      - visual-studio-code-bin
      - pycharm-professional
      - webstorm-jre
      - gitkraken
  become: yes
  become_user: aur_builder

