---
- name: Update packages
  pacman: 
    update-cache: yes
    upgrade: yes

- name: Install terminal font
  pacman: 
    name: terminus-font

- name: Globally set up vconsole font and keymap(=us)
  copy: 
    src: vconsole.conf 
    dest: /etc/vconsole.conf

- name: Install sudo, polkit
  pacman:
      name: sudo polkit

- name: Allow wheel group to use run sudo 
  lineinfile:
     path: /etc/sudoers.d/01_wheel
     state: present
     line: "%wheel ALL=(ALL) ALL"
     validate: /usr/sbin/visudo -cf %s
     create: yes    

- name: Install generic utilities
  pacman:
    name: tree rsync zip unzip base-devel dosfstools ntfs-3g openssh

- name: Create new user
  user:
    name: michael
    shell: /bin/bash
    groups: wheel
    createhome: yes
    generate_ssh_key: yes
    append: yes

- name: Create user for aur to install 
  user: 
    name: aur_builder

- name: Allow aur builder user to create items
  lineinfile:
     path: /etc/sudoers.d/02_aur_builder-allow-to-sudo-pacman
     state: present
     line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
     validate: /usr/sbin/visudo -cf %s
     create: yes    

- name: Install yay, pacman utility
  aur:
    name: yay
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder

- name: Enable ssh
  systemd:
    name: sshd.socket
    enabled: yes
    state: started
